name: Web UI Automation (demo)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-web-ui-auto-DEMO:
    runs-on: ubuntu-latest

    steps:
    # download repo
    - uses: actions/checkout@v4
    
    #setup java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    #setup browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2

    #setup gradle
    - name: Setup Gradlew
      run: chmod +x gradlew

    #execute gradlew command for running cucumber test
    - name: Execute Test
      run: ./gradlew webTest

    #execute gradlew command for running cucumber test
    - name: Execute Test
      run: ./gradlew apiTest

    #archive test result
    - name: Archive Test Result
      uses: actions/upload-artifact@v3.2.1-node20
      if: always()
      with: 
        name: Cucumber Report
        path: reports

    # deploy to github pages
    - name: Deploy Report To Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
       personal_token: ${{ secrets.SECRET_TOKEN }}
       publish_dir: reports
